server.port=8010

spring.datasource.url=jdbc:mariadb://localhost:8042/tourism_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tp
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.data.redis.port=8044
spring.cache.type=redis
spring.data.redis.host=localhost

logging.level.root=INFO
logging.level.lk.tourism.tourism_api_2026.controller=TRACE
logging.level.lk.tourism.tourism_api_2026.service=DEBUG
